recipe: default.v1
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

language: id #indonesia
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer #Creates bag-of-words representation of user messages, intents, and responses.
  - name: CountVectorsFeaturizer 
    analyzer: char_wb #character n-grams only from text inside word boundaries
    min_ngram: 1 #The lower boundary of the range of n-values for different word n-grams or char n-grams to be extracted.
    max_ngram: 4 #The Upper boundary of the range of n-values for different word n-grams or char n-grams to be extracted.
  - name: DIETClassifier #For intent and entities recognition
    epochs: 100 #This parameter sets the number of times the algorithm will see the training data
  - name: ResponseSelector
    epochs: 100 #This parameter sets the number of times the algorithm will see the training data
  - name: FallbackClassifier #Classifies a user message with the intent nlu_fallback in case the previous intent classifier wasn't able to classify an intent with a confidence greater or equal than the threshold of the FallbackClassifier
    threshold: 0.7 #Sets the threshold for predicting the nlu_fallback

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: RulePolicy #Handles conversation parts that follow a fixed behavior
  - name: UnexpecTEDIntentPolicy #Review conversations and also allows your bot to react to unlikely user turns.
    max_history: 5 #This parameter controls how much dialogue history the model looks at to decide which action to take next.
    epochs: 100 #This parameter sets the number of times the algorithm will see the training data