language: id
pipeline:
  - name: WhitespaceTokenizer #Creates a token for every whitespace separated character sequence.
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200